# Game variables, config stuff, data for adjusting things will go here
from pathlib import Path
import math

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = int(0.5 * SCREEN_WIDTH)

FPS = 60

BLACK = (0, 0, 0)
DARK_BLUE = (2, 24, 43) 
LIGHT_TURQUOISE = (104, 197, 219) 
LIGHT_BLUE = (1, 151, 246)

SCALE = 3

STARTING_ANGULAR_AMPLITUDE = 30
MAXIMUM_ANGULAR_AMPLITUDE = 180

ANGLE_STEP = (MAXIMUM_ANGULAR_AMPLITUDE - STARTING_ANGULAR_AMPLITUDE) / (FPS * 50)
COLLISION_ANGLE_DEDUCTION = 10

# Paths
BASE_DIR = Path(__file__).resolve().parent
IMG_DIR = BASE_DIR / "img"
ANIMATION_DIR = IMG_DIR / "animation"
DATA_DIR = BASE_DIR / "data"
PARTICLES_DIR = IMG_DIR / "particles"

POSITRON_EXPLODING_DIR = ANIMATION_DIR / "positron_exploding"

# Audio
SOUND_DIR = BASE_DIR / "sound"
VOLUME = 0.1

# Font
FONT_DIR = BASE_DIR / "fonts"
TITLE_FONT = FONT_DIR / "PixelifySans-Regular.ttf"
SCORE_FONT = FONT_DIR / "PixelOperatorMono8.ttf"

FONT = SCORE_FONT

FONT_SIZE = 30
SCORE_POS = (SCREEN_WIDTH - 100, 10)
FONT_COLOR = LIGHT_BLUE

COORDINATE_POS = (600, 10)

DOF_POS = (SCREEN_WIDTH - 275, SCREEN_HEIGHT - 50)

# Tiles
TILE_PADDING = 35
TILE_SIZE = 32

# Screen
SCREEN_SHAKE_MAGNITUDE = 3

# Player
REVERSE_VELOCITY = 5

PLAYER_START_X = 0
PLAYER_START_Y = 1850

INITIAL_ACCELERATION = 15
FRICTION = 1

DISPLACEMENT_SCALE = 0.25

ELECTRON_ROTATION = math.radians(3)
MIN_ROTATION = 0.0001

# Enemy
ENEMY_DAMAGE = 20

# Healthbar
HEALTH_PADDING = 10
HEALTHBAR_X = 50
HEALTHBAR_Y = 10
HEALTH_SCALE = 1.5

# Particles
VIBRATION_COOLDOWN = 50
PLAYER_VIBRATION_VELOCITY = 4
ENEMY_VIBRATION_VELOCITY = 2
VIBRATION_LIMIT = 20

HITBOX_RATIO = 2.5

MINIMUM_ATTRACTION_DISTANCE = 75
MAXIMUM_ATTRACTION_DISTANCE = 350

ATTRACTION_SPEED = 0.6

# Arrow
ARROW_SCALE = 2
INDICATOR_SCALE = 5
INDICATOR_TRANSPARENCY = 30