# Game variables, config stuff, data for adjusting things will go here
from pathlib import Path
import math

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

FPS = 60

BLACK = (0, 0, 0)
DARK_BLUE = (2, 24, 43) 
LIGHT_TURQUOISE = (104, 197, 219) 
LIGHT_BLUE = (1, 151, 246)
OFF_RED = (215, 38, 61)
DEFAULT_SCALE = 3

STARTING_ANGULAR_AMPLITUDE = 30
MAXIMUM_ANGULAR_AMPLITUDE = 180

ANGLE_STEP = (MAXIMUM_ANGULAR_AMPLITUDE - STARTING_ANGULAR_AMPLITUDE) / (FPS * 30)
COLLISION_ANGLE_DEDUCTION = 10
COLLISION_ANGLE_DEDUCTION_RATIO = 0.2

# Cursor
CURSOR_SCALE = 1.5

# Paths
BASE_DIR = Path(__file__).resolve().parent
IMG_DIR = BASE_DIR / "img"
ANIMATION_DIR = IMG_DIR / "animation"
DATA_DIR = BASE_DIR / "data"
PARTICLES_DIR = IMG_DIR / "particles"

POSITRON_EXPLODING_DIR = ANIMATION_DIR / "positron_exploding"
ELECTRON_EXPLODING_DIR = ANIMATION_DIR / "electron_exploding"
ANGLE_DIMINISHING_DIR = ANIMATION_DIR / "angle_diminishing"
HEALTH_DIMINISHING_DIR = ANIMATION_DIR / "health_diminishing"

# Audio
SOUND_DIR = BASE_DIR / "sound"
VOLUME = 0.1

# Font
FONT_DIR = BASE_DIR / "fonts"
TITLE_FONT = FONT_DIR / "PixelifySans-Regular.ttf"
SCORE_FONT = FONT_DIR / "PixelOperatorMono8.ttf"

FONT = SCORE_FONT

FONT_SIZE = 30
SCORE_POS = (SCREEN_WIDTH - 400, 200)
FONT_COLOR = LIGHT_BLUE

COORDINATE_POS = (600, 10)

DOF_POS = (SCREEN_WIDTH - 500, SCREEN_HEIGHT - 200)

# Tiles
TILE_PADDING = 35
TILE_SIZE = 32
CHUNK_SIZE = (TILE_PADDING + TILE_SIZE) * 100

LIMIT_BOTTOM = 2800
LIMIT_TOP = 1300

# Screen
SCREEN_SHAKE_MAGNITUDE = 5

SCANLINE_STEP = 3
PIXELATION_SCALE = 2
GLOW_SCALE = 3

GLITCH_EFFECT_OFFSET = 20
GLITCH_EFFECT_WIDTH = 10
MIN_SLICE = 5
MAX_SLICE = 20

STATIC_CHANCE = 0.003
STATIC_STEP = 8

# Player
REVERSE_VELOCITY = 10

PLAYER_START_X = -CHUNK_SIZE
PLAYER_START_Y = 2000

INITIAL_ACCELERATION = 15
FRICTION = 1

MAX_HEALTH = 140
INITIAL_HEALTH = 100

DISPLACEMENT_SCALE = 0.25

ELECTRON_ROTATION = math.radians(3)
MIN_ROTATION = 0.0001

# Enemy
ENEMY_DAMAGE = 20

# Healthbar
HEALTH_PADDING = 10
HEALTHBAR_X = 300
HEALTHBAR_Y = 200
HEALTH_SCALE = 1.5

# Particles
VIBRATION_COOLDOWN = 50
PLAYER_VIBRATION_VELOCITY = 2
ENEMY_VIBRATION_VELOCITY = 3
VIBRATION_LIMIT = 20

HITBOX_RATIO = 2.5

MINIMUM_ATTRACTION_DISTANCE = 60
MAXIMUM_ATTRACTION_DISTANCE = 450

ATTRACTION_SPEED = 0.6

EASY_ATTRACTION_SPEED = 0.6
MEDIUM_ATTRACTION_SPEED = 0.8
HARD_ATTRACTION_SPEED = 1.0

# Arrow
ARROW_SCALE = 2
INDICATOR_SCALE = 5
INDICATOR_TRANSPARENCY = 30

# Items
ITEM_SCALE = 2
HEALTH_ITEM_EFFECT = 20
ANGLE_ITEM_EFFECT = 30